# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
          . /etc/bashrc
        fi
export PATH=/opt/kube/bin:$PATH # generated by kubeasz
source <(kubectl completion bash)
source <(helm completion bash)
alias helms='helm --tls --tiller-namespace kube-system'
alias kls='kubectl get po --all-namespaces -o wide'
alias k='kubectl'
alias ks='kubectl get po'

#change the pwd configuration to an arrow
export PS1="\e[0;33m\A \e[0;36m[\h \w]\e[0;31m\$(parse_git_branch)\e[01;37m λ \e[m"
export TERM=xterm-256color

alias vi="vim"
alias py="python"

alias d:ps="docker ps"

#Nginx server
alias ng-conf="sudo vim /usr/local/etc/nginx/nginx.conf"
alias ng="sudo nginx"
alias ng-sd="sudo nginx -s stop"

#----------My shell shortcut--------------#
alias rc='vim ~/.bashrc'
alias src='source ~/.bash_profile'
alias vimrc='vim ~/.vimrc'

alias bc='cd -'
alias ll='ls -l'
alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias cl='clear'

# add alias for apache virtual host
alias apc-server='cd /etc/apache2/ && sudo vim .'
# alias apc-rs='sudo service apache2 restart'
alias apc-rs='sudo apachectl restart'
alias apc-host='sudo vim /etc/hosts'
alias apc-vhost='sudo vim /etc/apache2/extra/httpd-vhosts.conf'
alias apc-conf='sudo vim /etc/apache2/httpd.conf'


alias down='cd ~/Downloads/'
alias des='cd ~/Desktop'

#start mysql server
alias mysql-st='mysql.server start'
alias mysql-sd='mysql.server stop'

alias ssh-repo='ssh root@10.210.10.139'
alias ssh-mg='ssh root@10.210.10.35'

#alias ssh-built='ssh -i ~/.ssh/built admin@139.162.22.77'
#alias ssh-vv='ssh -i ~/.ssh/vv -p 2683 virtualv@c3s4-2e-syd.hosting-services.net.au'

# alias for git
alias git-conf='vim ~/.gitconfig'
alias gs="git status"
alias gc="git checkout"
alias gcb="git checkout -branch"
alias gmf="git merge --no-ff"
alias gcm='git commit -m'
alias ga="git add --all"
alias gp="git push"

#--------------My shell scripts---------------#

#config the git branch 
parse_git_branch() 
{
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
  
